
clone_folder: C:\projects\bkbtl-qt
shallow_clone: true

# See https://www.appveyor.com/docs/windows-images-software/#qt
environment:
  matrix:
    - QTDIR: C:\Qt\5.6.3\mingw49_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.6.3\msvc2013
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.6.3\msvc2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.6.3\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.7\mingw53_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.7\msvc2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.9\mingw53_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.9\msvc2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.9\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.10\mingw53_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.10\msvc2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.10\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.11\mingw53_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.11\msvc2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.11\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.12\mingw73_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.12\mingw73_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.12\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.13\mingw73_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.13\mingw73_32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - QTDIR: C:\Qt\5.13\msvc2015_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#    - QTDIR: C:\Qt\5.14\msvc2017_64
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    - QTDIR: C:\Qt\5.15\mingw81_64
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    - QTDIR: C:\Qt\5.15\mingw81_32
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - QTDIR: C:\Qt\5.15\msvc2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - QTDIR: C:\Qt\5.15\msvc2019_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

configuration:
  - debug
  - release

matrix:
  exclude:
    - QTDIR: C:\Qt\5.6.3\msvc2015
      configuration: debug
    - QTDIR: C:\Qt\5.6.3\msvc2015_64
      configuration: debug
    - QTDIR: C:\Qt\5.9\msvc2015
      configuration: debug
    - QTDIR: C:\Qt\5.9\msvc2015_64
      configuration: debug
    - QTDIR: C:\Qt\5.10\msvc2015
      configuration: debug
    - QTDIR: C:\Qt\5.10\msvc2015_64
      configuration: debug
    - QTDIR: C:\Qt\5.11\msvc2015
      configuration: debug
    - QTDIR: C:\Qt\5.11\msvc2015_64
      configuration: debug

init:
  - git config --global core.autocrlf input

install:
  # Setup the build toolchains
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2019=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'

