name: PVS-Studio analysis

on: workflow_dispatch

jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        install-deps: 'true'
        modules: 'qtscript'
    - name: Install PVS Studio
      run: |
        wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt | sudo apt-key add -
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.pvs-studio.com/etc/viva64.list
        sudo apt update
        sudo apt install pvs-studio
        pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}
    - name: Prepare JSON
      run: |
        sudo apt install bear
        qmake "CONFIG+=debug" QtBkBtl.pro
        bear -- make
    - name: Analyze
      run: |
        pvs-studio-analyzer analyze -f compile_commands.json --quiet
      continue-on-error: true
    - name: Convert
      run: |
        mkdir Results
        plog-converter -t html,totals -o ./Results/ ./PVS-Studio.log
    - name: Upload the report
      uses: actions/upload-artifact@v3
      with:
        name: BkBtlQt-PVS
        path: ./Results/
